In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
    print('GPU is available')
    print(f'{torch.cuda.get_device_name(0)}')
else :
    print('GPU is not available')

GPU is available
Tesla T4


Tensor


In [ ]:
a=torch.empty(2,3)
print(type(a))

<class 'torch.Tensor'>


In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(3,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])

In [ ]:
torch.arange(0,10,3)

tensor([0, 3, 6, 9])

In [ ]:
torch.linspace(1,15,7)

tensor([ 1.0000,  3.3333,  5.6667,  8.0000, 10.3333, 12.6667, 15.0000])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.full((3,4),5,dtype=torch.float32)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [ ]:
a=torch.tensor([[2,3,4],[4,5,6]],dtype=torch.int32)
a

tensor([[2, 3, 4],
        [4, 5, 6]], dtype=torch.int32)

In [ ]:
print(torch.empty_like(a,dtype=torch.int32))
print(torch.zeros_like(a,dtype=torch.int32))
print(torch.ones_like(a,dtype=torch.int32))
print(torch.rand_like(a,dtype=torch.float32))


tensor([[1688796528,      31535,  424314496],
        [         0,          0,          0]], dtype=torch.int32)
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [ ]:
a+5

tensor([[ 7,  8,  9],
        [ 9, 10, 11]])

In [ ]:
a-100

tensor([[-98, -97, -96],
        [-96, -95, -94]])

In [ ]:
a*100

tensor([[200, 300, 400],
        [400, 500, 600]])

In [ ]:
b=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)

In [ ]:
a+b

tensor([[ 3.,  5.,  7.],
        [ 8., 10., 12.]])

In [ ]:
a*b

tensor([[ 2.,  6., 12.],
        [16., 25., 36.]])

In [ ]:
b=b.reshape(3,2)
b=b.to(torch.int32)
torch.matmul(a,b)

tensor([[31, 40],
        [49, 64]], dtype=torch.int32)

In [ ]:
c=torch.rand(2,3)
c

tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])

In [ ]:
c[0][0]=-1
c

tensor([[-1.0000,  0.7064,  0.1629],
        [ 0.8902,  0.5163,  0.0359]])

In [ ]:
print(torch.abs(c))
print(torch.neg(c))
print(torch.round(c))
print(torch.exp(c))
print(torch.log(c))
print(torch.sqrt(c))
print(torch.ceil(c))
print(torch.floor(c))

print(torch.sigmoid(c))
print(torch.tanh(c))
print(torch.softmax(c, dim=0))
print(torch.relu(c))

tensor([[1.0000, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])
tensor([[ 1.0000, -0.7064, -0.1629],
        [-0.8902, -0.5163, -0.0359]])
tensor([[-1.,  1.,  0.],
        [ 1.,  1.,  0.]])
tensor([[0.3679, 2.0267, 1.1769],
        [2.4356, 1.6758, 1.0365]])
tensor([[    nan, -0.3476, -1.8148],
        [-0.1163, -0.6611, -3.3274]])
tensor([[   nan, 0.8405, 0.4036],
        [0.9435, 0.7185, 0.1894]])
tensor([[-1.,  1.,  1.],
        [ 1.,  1.,  1.]])
tensor([[-1.,  0.,  0.],
        [ 0.,  0.,  0.]])
tensor([[0.2689, 0.6696, 0.5406],
        [0.7089, 0.6263, 0.5090]])
tensor([[-0.7616,  0.6084,  0.1615],
        [ 0.7115,  0.4748,  0.0359]])
tensor([[0.1312, 0.5474, 0.5317],
        [0.8688, 0.4526, 0.4683]])
tensor([[0.0000, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])


In [ ]:
print(torch.mean(c))
print(torch.mean(c, dim=0))
print(torch.mean(c, dim=1))
print(torch.sum(c))
print(torch.var(c))
print(torch.std(c))
print(torch.argmax(c))
print(torch.argmin(c))
print(torch.max(c))
print(torch.min(c))

tensor(0.2186)
tensor([-0.0549,  0.6113,  0.0994])
tensor([-0.0436,  0.4808])
tensor(1.3116)
tensor(0.4598)
tensor(0.6781)
tensor(3)
tensor(0)
tensor(0.8902)
tensor(-1.)


In [ ]:
d=torch.rand(3,3)

print(torch.det(d))
print(torch.inverse(d))
# print(torch.svd(d))

tensor(0.1295)
tensor([[-1.2074,  0.4460,  2.0138],
        [ 1.6047, -0.8104,  0.0323],
        [-1.1520,  3.0965, -1.9277]])


In [ ]:
b=b.reshape(2,3)

In [ ]:
a>b

tensor([[ True,  True,  True],
        [False, False, False]])

In [ ]:
a.add_(5)

tensor([[ 7,  8,  9],
        [ 9, 10, 11]], dtype=torch.int32)

In [ ]:
e=a.clone()
e[0][0]=100
print(e)
print(a)

tensor([[100,   8,   9],
        [  9,  10,  11]], dtype=torch.int32)
tensor([[ 7,  8,  9],
        [ 9, 10, 11]], dtype=torch.int32)


In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [ ]:
df.drop(['id','Unnamed: 32'],axis=1, inplace=True)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(455, 30)
(114, 30)
(455,)
(114,)


In [ ]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
y_train

,diagnosis
301,B
302,M
64,M
321,M
360,B
...,...
446,M
317,M
452,B
118,M


In [ ]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [ ]:
y_train

array([0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,

In [ ]:
X_train=torch.from_numpy(X_train.astype(np.float32))
X_test=torch.from_numpy(X_test.astype(np.float32))
y_train=torch.from_numpy(y_train.astype(np.float32))
y_test=torch.from_numpy(y_test.astype(np.float32))

Defining Model

In [ ]:
class MyNN():
    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,requires_grad=True)
        self.bias=torch.rand(1,requires_grad=True)

    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train * torch.log(y_pred) + (1 - y_train) * torch.log(1 - y_pred)).mean()
        return loss

In [ ]:
learning_rate=0.2
epochs=1000

Training Pipeline

In [ ]:
model = MyNN(X_train)

for epoch in range(epochs):
    y_pred = model.forward(X_train)
    loss = model.loss_function(y_pred, y_train)

    loss.backward()
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

        model.weights.grad.zero_()
        model.bias.grad.zero_()

        print(f'Epoch: {epoch+1}, Loss: {loss.item():.4f}')


Epoch: 1, Loss: 3.5047
Epoch: 2, Loss: 3.2592
Epoch: 3, Loss: 2.9941
Epoch: 4, Loss: 2.7055
Epoch: 5, Loss: 2.4072
Epoch: 6, Loss: 2.1032
Epoch: 7, Loss: 1.8025
Epoch: 8, Loss: 1.5339
Epoch: 9, Loss: 1.3155
Epoch: 10, Loss: 1.1420
Epoch: 11, Loss: 1.0245
Epoch: 12, Loss: 0.9508
Epoch: 13, Loss: 0.9044
Epoch: 14, Loss: 0.8726
Epoch: 15, Loss: 0.8481
Epoch: 16, Loss: 0.8275
Epoch: 17, Loss: 0.8094
Epoch: 18, Loss: 0.7933
Epoch: 19, Loss: 0.7789
Epoch: 20, Loss: 0.7660
Epoch: 21, Loss: 0.7546
Epoch: 22, Loss: 0.7444
Epoch: 23, Loss: 0.7353
Epoch: 24, Loss: 0.7273
Epoch: 25, Loss: 0.7202
Epoch: 26, Loss: 0.7138
Epoch: 27, Loss: 0.7082
Epoch: 28, Loss: 0.7032
Epoch: 29, Loss: 0.6988
Epoch: 30, Loss: 0.6948
Epoch: 31, Loss: 0.6912
Epoch: 32, Loss: 0.6880
Epoch: 33, Loss: 0.6852
Epoch: 34, Loss: 0.6826
Epoch: 35, Loss: 0.6803
Epoch: 36, Loss: 0.6782
Epoch: 37, Loss: 0.6763
Epoch: 38, Loss: 0.6745
Epoch: 39, Loss: 0.6730
Epoch: 40, Loss: 0.6715
Epoch: 41, Loss: 0.6702
Epoch: 42, Loss: 0.6690
E

Evaluation


In [ ]:
with torch.no_grad():
    y_pred=model.forward(X_test)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test).float().mean()
    print(f'Accuracy : {accuracy}')


Accuracy : 0.5350877046585083


NN Module

In [ ]:
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out


Updated the previous code with NN module and dataset and Dataloader module


In [ ]:
import torch
import torch.nn as nn

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

torch.Size([455, 30])
torch.Size([455])
torch.Size([114, 30])
torch.Size([114])


In [ ]:
from torch.utils.data import Dataset

class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]


train_dataset = CustomDataset(X_train, y_train)
test_dataset = CustomDataset(X_test, y_test)

In [ ]:
from torch.utils.data import DataLoader

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [ ]:
class MyNN2(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,1),
            nn.Sigmoid(),
        )

    def forward(self,features):
        y_pred = self.network(features)
        return y_pred


In [ ]:
learning_rate = 0.2
epochs = 25

loss_function = nn.BCELoss()

In [ ]:
model = MyNN2(X_train.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):

    for batch_of_features,batch_of_labels in train_loader:

        y_pred=model(batch_of_features)
        loss = loss_function(y_pred, batch_of_labels.view(-1, 1))

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        print(f'Epoch: {epoch+1} loss: {loss.item()}')

Epoch: 1 loss: 0.6955851316452026
Epoch: 1 loss: 0.43011727929115295
Epoch: 1 loss: 0.3309195339679718
Epoch: 1 loss: 0.3858216404914856
Epoch: 1 loss: 0.3226381838321686
Epoch: 1 loss: 0.2041686773300171
Epoch: 1 loss: 0.3095111846923828
Epoch: 1 loss: 0.28882455825805664
Epoch: 1 loss: 0.16198326647281647
Epoch: 1 loss: 0.17276009917259216
Epoch: 1 loss: 0.14564841985702515
Epoch: 1 loss: 0.1178172379732132
Epoch: 1 loss: 0.1329466700553894
Epoch: 1 loss: 0.1796359121799469
Epoch: 1 loss: 0.09154941141605377
Epoch: 2 loss: 0.10673831403255463
Epoch: 2 loss: 0.1953454464673996
Epoch: 2 loss: 0.08474699407815933
Epoch: 2 loss: 0.17226648330688477
Epoch: 2 loss: 0.16532331705093384
Epoch: 2 loss: 0.13711366057395935
Epoch: 2 loss: 0.19729070365428925
Epoch: 2 loss: 0.10790351033210754
Epoch: 2 loss: 0.1100030392408371
Epoch: 2 loss: 0.1603938490152359
Epoch: 2 loss: 0.09582215547561646
Epoch: 2 loss: 0.13589513301849365
Epoch: 2 loss: 0.19160565733909607
Epoch: 2 loss: 0.135612294077873

In [ ]:
# Model Evaluation

model.eval()
accuracy_list = []

with torch.no_grad():
    for batch_of_features, batch_of_labels in test_loader:

        y_pred = model.forward(batch_of_features)
        y_pred = (y_pred > 0.8).float()

        batch_accuracy = (y_pred == batch_of_labels.view(-1, 1)).float().mean().item()
        accuracy_list.append(batch_accuracy)

overall_acccuracy = sum(accuracy_list)/len(accuracy_list)
print(f'Accuracy: {overall_acccuracy:.4f}')

Accuracy: 0.9766
